version: "3.7"

services:
  web:
    build: ./app/django-doubtfire-api/
    command: >
        bash -c "python3 manage.py runserver 0.0.0.0:8000 
        & celery -A api worker --loglevel=INFO"
    volumes:
      - ./app/django-doubtfire-api/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
  redis:
    image: redis:6.0.10-buster
    volumes: 
      - redis:/data
    env_file:
      - ./.env.dev

volumes:
  postgres_data:
  redis: 
